// Generated by CoffeeScript 1.9.3
(function() {
  var colorIndices, colors, gradientSpeed, may, step, updateGradient, now;

  updateGradient = function() {
    var b1, b2, c0_0, c0_1, c1_0, c1_1, color1, color2, g1, g2, istep, r1, r2;
    if ($ === undefined) {
      return;
    }
    c0_0 = colors[colorIndices[0]];
    c0_1 = colors[colorIndices[1]];
    c1_0 = colors[colorIndices[2]];
    c1_1 = colors[colorIndices[3]];
    istep = 1 - step;
    r1 = Math.round(istep * c0_0[0] + step * c0_1[0]);
    g1 = Math.round(istep * c0_0[1] + step * c0_1[1]);
    b1 = Math.round(istep * c0_0[2] + step * c0_1[2]);
    color1 = "rgb(" + r1 + "," + g1 + "," + b1 + ")";
    r2 = Math.round(istep * c1_0[0] + step * c1_1[0]);
    g2 = Math.round(istep * c1_0[1] + step * c1_1[1]);
    b2 = Math.round(istep * c1_0[2] + step * c1_1[2]);
    color2 = "rgb(" + r2 + "," + g2 + "," + b2 + ")";
    $("#bannertext").css({
      background: "-webkit-gradient(linear, left top, right top, from(" + color1 + "), to(" + color2 + "))"
    }).css({
      background: "-moz-linear-gradient(left, " + color1 + " 0%, " + color2 + " 100%)"
    }).css({
      background: "-o-linear-gradient(left, " + color1 + " 0%, " + color2 + " 100%)"
    }).css({
      background: "linear-gradient(left, " + color1 + " 0%, " + color2 + " 100%)"
    }).css;
    step += gradientSpeed;
    if (step >= 1) {
      step %= 1;
      colorIndices[0] = colorIndices[1];
      colorIndices[2] = colorIndices[3];
      colorIndices[1] = (colorIndices[1] + Math.floor(1 + Math.random() * (colors.length - 1))) % colors.length;
      return colorIndices[3] = (colorIndices[3] + Math.floor(1 + Math.random() * (colors.length - 1))) % colors.length;
    }
  };

  colors = [[62, 35, 255], [255, 35, 98], [45, 175, 230], [255, 0, 255], [255, 128, 0]];

  step = 0;

  colorIndices = [0, 1, 2, 3];

  gradientSpeed = 0.003;

  setInterval(updateGradient, 10);

  $("#scrolling_text").liMarquee();

  (function($) {
    $.countdown.regionalOptions["ru"] = {
      labels: ["Лет", "Месяцев", "Недель", "Дней", "Часов", "Минут", "Секунд"],
      labels1: ["Год", "Месяц", "Неделя", "День", "Час", "Минута", "Секунда"],
      labels2: ["Года", "Месяца", "Недели", "Дня", "Часа", "Минуты", "Секунды"],
      compactLabels: ["л", "м", "н", "д"],
      compactLabels1: ["г", "м", "н", "д"],
      whichLabels: function(amount) {
        var tens, units;
        units = amount % 10;
        tens = Math.floor((amount % 100) / 10);
        if (amount === 1) {
          return 1;
        } else {
          if (units >= 2 && units <= 4 && tens !== 1) {
            return 2;
          } else {
            if (units === 1 && tens !== 1) {
              return 1;
            } else {
              return 0;
            }
          }
        }
      },
      digits: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
      timeSeparator: ":",
      isRTL: false
    };
    return $.countdown.setDefaults($.countdown.regionalOptions["ru"]);
  })(jQuery);

  //may = new Date("2016", "4", "9");
  //now = new Date();

  //if (now.getDate() >= may.getDate()) {
    //$(".banner_image4").removeClass("banner_image4").addClass("banner_image5");
  //} else {
    //$(".banner_timer").countdown({
      //until: may,
      //timezone: +3,
      //description: "до дня Великой Победы осталось"
    //});
  //}

  $(document).ready(function() {
    $('audio').on('pause', function(event) {
      event = event || window.event;
      target = event.target || event.srcElement;
      src = target.currentSrc;
      target.currentSrc = "";
      target.src = src;
    });
  });

}).call(this);
